sidebar_title: "ce-amtic's."
sidebar_subtitle: "眩しくて、知らなくて、<br>恐ろしくて ..."

truncate_len: 180

rss: atom.xml

favicon: /img/favicon.ico

# Customize the sidebar nav menu
menu:
    Search: /search
    Categories: /categories
    Tags: /tags
    Archive: /archives
    About: /about

cdn:
    # Support public CDN names: cdnjs, loli, baomitu, unpkg, jsdelivr
    libs: cdnjs
    # The base URL of Google Fonts CDN (e.g. "https://fonts.loli.net" "https://fonts.googleapis.com")
    fonts: https://fonts.loli.net

hljsTheme: atom-one-light

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] for livere.com
disqus: # [short_name] for disqus.com
giscus:
    # Use the official giscus app
    app: https://giscus.app/client.js

    # The options, see "Enable giscus" section in https://giscus.app/
    repo: ce-amtic/ce-amtic.github.io # [ENTER REPO HERE]
    repo-id: MDEwOlJlcG9zaXRvcnkxNjgzNTYwMTE= # [ENTER REPO ID HERE]
    category: General # [ENTER CATEGORY NAME HERE]
    category-id: DIC_kwDOCgjoq84CVvut # [ENTER CATEGORY ID HERE]
    mapping: pathname
    reactions-enabled: 1
    emit-metadata: 0
    theme: light
    lang: en
